<?php

namespace Database\Seeders;

use App\Models\Disease;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $diseases = [
            "MDD",
            "Thought disorder",
            "Delusional Disorder",
            "Cenesthopathic schizophrenia",
            "Simple schizophrenia",
            "Residual schizophrenia",
            "Disorganized schizophrenia",
            "Claustrophobia",
            "Cynophobia",
            "Gynophobia",
            "MDD",
            "Loneliness",
            "Bipolar",
            "Anexity",
            "PTSD",
            "Sleeping Disorder",
            "Psychotic Disorder",
            "ADHD",
            "PDD",
            "OCD",
            "Depression",
            "Stress",
            "Personality Disorder",
            "Schizophreniq",
            "Addictive Behaviors",
            "Confused Thinking",
            "Anger Issues",
            "Phobias",
            "Panic Disorder",
            "Necrophobia",
            "Amaxophobia",
            "Bathmophobia",
            "Dentophobia",
            "Coulrophobia",
            "Belonephobia",
            "Brontophobia",
            "Gephyrophobia",
            "Odontiatophobia",
            "Phartophobia",
            "Phasmophobia",
            "Phobophobia",
            "Trypanophobia",
            "Trypophobia",
            "Stendhal Syndrome",
            "Factitious Disorder",
            "Apotemnophilia",
            "Attention Deficit Hyperactivity Disorder",
            "Autophagia",
            "Avoidant Personality Disorder",
            "Capgras syndrome",
            "Alien Hand Syndrome",
            "Cotard syndrome",
            "phantom pain syndrome",
            "Foreign accent syndrome",
            "MDD",
            "Loneliness",
            "Acute Srtess Disorder",
            "Adjustement Disorder",
            "Bulimia Nervosa",
            "Anorexia Nervosa",
            "Borderline Personality Disorder",
            "Antisocial Personality Disorder",
            "Narcissistic Personality Disorder",
            "Dissocative identity disorder",
            "Truma and stress related disorder",
            "Guilt Syndrome",
            "Agoraphobia",
            "Separation Anxity",
            "Conversion Disorder",
            "Passive-Aggressive Personality Disorder",
            "Paranoia",
            "Shared Psychotic Disorder",
            "Acrophobia",
            "Aerophobia",
            "Arachnophobia",
            "Bacteriophobia",
            "Lockiophobia",
            "Mysophobia",
            "Ophidiophobia",
            "Social phobia",
            "Zoophobia",
            "Aquaphobia",
            "Amok",
            "Latah",
            "Piblokto",
            "Cyclothymic disorder",
            "PMDD",
            "Premenstrual syndrome",
            "Dissociative amnesia",
            "Depersonalization/derealization disorder",
            "Isnomnia Disorder",
            "Psychopatic",
            "Postpartum depression",
            "BPD Borderline Personality Disorder",
            "Chronic Fatigue Syndrome",
            "OCPD",
            "Guilt Syndrome",
            "Agoraphobia",
            "Separation Anxity",
            "Conversion Disorder",
            "Passive-Aggressive Personality Disorder",
            "Paranoia",
            "Shared Psychotic Disorder",
            "Acrophobia",
            "Aerophobia",
            "Arachnophobia",
            "Bacteriophobia",
            "Lockiophobia",
            "Mysophobia",
            "Ophidiophobia",
            "Social phobia",
            "Zoophobia",
            "Aquaphobia",
            "Amok",
            "Latah",
            "Piblokto",
            "Thought disorder",
            "Delusional Disorder",
            "Cenesthopathic schizophrenia",
            "Simple schizophrenia",
            "Residual schizophrenia",
            "Disorganized schizophrenia",
            "Claustrophobia",
            "Cynophobia",
            "Gynophobia",
            "Necrophobia",
            "Amaxophobia",
            "Bathmophobia",
            "Dentophobia",
            "Coulrophobia",
            "Belonephobia",
            "Brontophobia",
            "Gephyrophobia",
            "Odontiatophobia",
            "Phartophobia",
            "Phasmophobia",
            "Phobophobia",
            "Trypanophobia",
            "Trypophobia",
            "Stendhal Syndrome",
            "Factitious Disorder",
            "Apotemnophilia",
            "Attention Deficit Hyperactivity Disorder",
            "Autophagia",
            "Avoidant Personality Disorder",
            "Capgras syndrome",
            "Alien Hand Syndrome",
            "Cotard syndrome",
            "phantom pain syndrome",
            "Foreign accent syndrome",
        ];

        $uniqueDieseases = array_unique($diseases);

        foreach ($uniqueDieseases as $disease) {
            Disease::create(['name' => $disease]);
        }
    }
}
